### PR TITLE
4.1.0 release

### PR DESCRIPTION
**Pull request by SeanEmac**

### CODE REVIEW

**Review by m62534 — APPROVED** [review]
checked around readmes related to notion changes
checked version number
checked configmap generator script

**Comment by SeanEmac** [comment]
daily_feed

**Comment by SeanEmac** [comment]
sprint_insights

**Comment by SeanEmac** [comment]
notion_preview

**Comment by SeanEmac** [comment]
pull_request_links

**Comment by SeanEmac** [comment]
dynamic_recommendations

**Pull request merged**
